server:
  port: ${PORT:8082}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: fitnessactivity
  rabbitmq:
    addresses: ${RABBITMQ_URL}

eureka:
  client:
    enabled: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
