server:
  port: ${PORT:8083}

spring:
  data:
    mongodb:
      uri: ${MONGODB_URI}
      database: fitnessrecommendations
  rabbitmq:
    addresses: ${RABBITMQ_URL}

groq:
  api:
    url: https://api.groq.com/openai/v1
    key: ${GROQ_API_KEY}

eureka:
  client:
    enabled: false

rabbitmq:
  exchange:
    name: fitness.exchange
  queue:
    name: activity.queue
  routing:
    key: activity.tracking
