server:
  port: ${PORT:8080}

spring:
  application:
    name: api-gateway

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:https://dev-ooryx7evb8kbyq1z.us.auth0.com/}
          jwk-set-uri: ${KEYCLOAK_JWK_URI:https://dev-ooryx7evb8kbyq1z.us.auth0.com/.well-known/jwks.json}

  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: user-service
              uri: ${USER_SERVICE_URL:lb://USER-SERVICE}
              predicates:
                - Path=/api/users/**

            - id: activity-service
              uri: ${ACTIVITY_SERVICE_URL:lb://ACTIVITY-SERVICE}
              predicates:
                - Path=/api/activities/**

            - id: ai-service
              uri: ${AI_SERVICE_URL:lb://AI-SERVICE}
              predicates:
                - Path=/api/recommendations/**

eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URL:http://eureka:8761/eureka/}
